"use client"

import React from "react"
import { format } from "date-fns"
import type { ReportData } from "@/lib/types/reports"

export type { ReportData }

interface ReportTemplateA4Props {
  report: ReportData
  sampleData?: any
}

export const ReportTemplateA4 = React.forwardRef<HTMLDivElement, ReportTemplateA4Props>(
  ({ report, sampleData }, ref) => {
    const formatDate = (date: Date | null) => {
      if (!date) return "N/A"
      return format(new Date(date), "MMMM dd, yyyy HH:mm")
    }

    const renderReportContent = () => {
      // Render different content based on report category
      switch (report.category?.toLowerCase()) {
        case "financial":
          return <FinancialReportContent report={report} data={sampleData} />
        case "patient":
          return <PatientReportContent report={report} data={sampleData} />
        case "staff":
          return <StaffReportContent report={report} data={sampleData} />
        case "operations":
          return <OperationsReportContent report={report} data={sampleData} />
        default:
          return <GenericReportContent report={report} data={sampleData} />
      }
    }

    return (
      <div
        ref={ref}
        className="bg-white text-black"
        style={{
          width: "210mm", // A4 width
          minHeight: "297mm", // A4 height
          padding: "20mm",
          margin: "0 auto",
          boxSizing: "border-box",
        }}
      >
        {/* Header */}
        <header className="border-b-2 border-gray-300 pb-4 mb-6">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 mb-1">
                Soddo Hospital
              </h1>
              <p className="text-sm text-gray-600">Hospital Management System</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-gray-500">Generated on</p>
              <p className="text-sm font-medium">{formatDate(new Date())}</p>
            </div>
          </div>
        </header>

        {/* Report Title Section */}
        <section className="mb-6">
          <h2 className="text-xl font-bold text-gray-900 mb-2">{report.title}</h2>
          {report.description && (
            <p className="text-sm text-gray-600 mb-4">{report.description}</p>
          )}

          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="font-semibold text-gray-700">Department:</span>{" "}
              <span className="text-gray-600">{report.department || "All Departments"}</span>
            </div>
            <div>
              <span className="font-semibold text-gray-700">Category:</span>{" "}
              <span className="text-gray-600">{report.category || "General"}</span>
            </div>
            <div>
              <span className="font-semibold text-gray-700">Frequency:</span>{" "}
              <span className="text-gray-600">{report.frequency}</span>
            </div>
            <div>
              <span className="font-semibold text-gray-700">Status:</span>{" "}
              <span className="text-gray-600">{report.status}</span>
            </div>
          </div>
        </section>

        {/* Report Content */}
        <section className="mb-6">
          {renderReportContent()}
        </section>

        {/* Footer */}
        <footer className="border-t-2 border-gray-300 pt-4 mt-8">
          <div className="text-xs text-gray-500 text-center">
            <p>This report was automatically generated by Soddo Hospital Management System</p>
            <p className="mt-1">
              Report ID: {report.id} | Generated: {formatDate(new Date())}
            </p>
          </div>
        </footer>
      </div>
    )
  }
)

ReportTemplateA4.displayName = "ReportTemplateA4"

// Financial Report Content
function FinancialReportContent({ report, data }: { report: ReportData; data?: any }) {
  const sampleData = data || {
    revenue: 125000,
    expenses: 95000,
    profit: 30000,
    transactions: [
      { date: "2024-01-15", description: "Patient Services", amount: 25000 },
      { date: "2024-01-20", description: "Laboratory Services", amount: 15000 },
      { date: "2024-01-25", description: "Medical Supplies", amount: -12000 },
    ],
  }

  return (
    <div>
      <h3 className="text-lg font-bold text-gray-900 mb-4">Financial Summary</h3>

      {/* Summary Cards */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Total Revenue</p>
          <p className="text-xl font-bold text-green-600">
            ${sampleData.revenue.toLocaleString()}
          </p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Total Expenses</p>
          <p className="text-xl font-bold text-red-600">
            ${sampleData.expenses.toLocaleString()}
          </p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Net Profit</p>
          <p className="text-xl font-bold text-blue-600">
            ${sampleData.profit.toLocaleString()}
          </p>
        </div>
      </div>

      {/* Transactions Table */}
      <h4 className="text-md font-semibold text-gray-900 mb-3">Recent Transactions</h4>
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2 px-3 font-semibold text-gray-700">Date</th>
            <th className="text-left py-2 px-3 font-semibold text-gray-700">Description</th>
            <th className="text-right py-2 px-3 font-semibold text-gray-700">Amount</th>
          </tr>
        </thead>
        <tbody>
          {sampleData.transactions.map((transaction: any, index: number) => (
            <tr key={index} className="border-b border-gray-200">
              <td className="py-2 px-3 text-gray-600">{transaction.date}</td>
              <td className="py-2 px-3 text-gray-600">{transaction.description}</td>
              <td className={`py-2 px-3 text-right font-medium ${
                transaction.amount >= 0 ? "text-green-600" : "text-red-600"
              }`}>
                ${Math.abs(transaction.amount).toLocaleString()}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// Patient Report Content
function PatientReportContent({ report, data }: { report: ReportData; data?: any }) {
  const sampleData = data || {
    totalPatients: 450,
    newPatients: 75,
    admissions: 120,
    discharges: 95,
    departments: [
      { name: "Emergency", count: 85 },
      { name: "Surgery", count: 45 },
      { name: "Pediatrics", count: 65 },
      { name: "Cardiology", count: 55 },
    ],
  }

  return (
    <div>
      <h3 className="text-lg font-bold text-gray-900 mb-4">Patient Statistics</h3>

      {/* Summary Cards */}
      <div className="grid grid-cols-4 gap-3 mb-6">
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Total Patients</p>
          <p className="text-xl font-bold text-blue-600">{sampleData.totalPatients}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">New Patients</p>
          <p className="text-xl font-bold text-green-600">{sampleData.newPatients}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Admissions</p>
          <p className="text-xl font-bold text-purple-600">{sampleData.admissions}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Discharges</p>
          <p className="text-xl font-bold text-orange-600">{sampleData.discharges}</p>
        </div>
      </div>

      {/* Department Breakdown */}
      <h4 className="text-md font-semibold text-gray-900 mb-3">Patients by Department</h4>
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2 px-3 font-semibold text-gray-700">Department</th>
            <th className="text-right py-2 px-3 font-semibold text-gray-700">Patient Count</th>
          </tr>
        </thead>
        <tbody>
          {sampleData.departments.map((dept: any, index: number) => (
            <tr key={index} className="border-b border-gray-200">
              <td className="py-2 px-3 text-gray-600">{dept.name}</td>
              <td className="py-2 px-3 text-right font-medium text-gray-900">{dept.count}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// Staff Report Content
function StaffReportContent({ report, data }: { report: ReportData; data?: any }) {
  const sampleData = data || {
    totalStaff: 250,
    doctors: 85,
    nurses: 120,
    admin: 45,
    departments: [
      { name: "Medical", count: 85, available: 80 },
      { name: "Nursing", count: 120, available: 115 },
      { name: "Administration", count: 45, available: 42 },
    ],
  }

  return (
    <div>
      <h3 className="text-lg font-bold text-gray-900 mb-4">Staff Report</h3>

      {/* Summary Cards */}
      <div className="grid grid-cols-4 gap-3 mb-6">
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Total Staff</p>
          <p className="text-xl font-bold text-blue-600">{sampleData.totalStaff}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Doctors</p>
          <p className="text-xl font-bold text-green-600">{sampleData.doctors}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Nurses</p>
          <p className="text-xl font-bold text-purple-600">{sampleData.nurses}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Admin Staff</p>
          <p className="text-xl font-bold text-orange-600">{sampleData.admin}</p>
        </div>
      </div>

      {/* Department Breakdown */}
      <h4 className="text-md font-semibold text-gray-900 mb-3">Staff by Department</h4>
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2 px-3 font-semibold text-gray-700">Department</th>
            <th className="text-right py-2 px-3 font-semibold text-gray-700">Total</th>
            <th className="text-right py-2 px-3 font-semibold text-gray-700">Available</th>
          </tr>
        </thead>
        <tbody>
          {sampleData.departments.map((dept: any, index: number) => (
            <tr key={index} className="border-b border-gray-200">
              <td className="py-2 px-3 text-gray-600">{dept.name}</td>
              <td className="py-2 px-3 text-right font-medium text-gray-900">{dept.count}</td>
              <td className="py-2 px-3 text-right font-medium text-green-600">{dept.available}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// Operations Report Content
function OperationsReportContent({ report, data }: { report: ReportData; data?: any }) {
  const sampleData = data || {
    surgeries: 45,
    emergencies: 120,
    bedOccupancy: 85,
    equipment: [
      { name: "MRI Machine", status: "Operational", usage: "85%" },
      { name: "CT Scanner", status: "Operational", usage: "92%" },
      { name: "X-Ray Unit 1", status: "Maintenance", usage: "0%" },
      { name: "Ultrasound", status: "Operational", usage: "78%" },
    ],
  }

  return (
    <div>
      <h3 className="text-lg font-bold text-gray-900 mb-4">Operations Report</h3>

      {/* Summary Cards */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Surgeries</p>
          <p className="text-xl font-bold text-blue-600">{sampleData.surgeries}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Emergencies</p>
          <p className="text-xl font-bold text-red-600">{sampleData.emergencies}</p>
        </div>
        <div className="border border-gray-300 rounded p-3">
          <p className="text-xs text-gray-600 mb-1">Bed Occupancy</p>
          <p className="text-xl font-bold text-green-600">{sampleData.bedOccupancy}%</p>
        </div>
      </div>

      {/* Equipment Status */}
      <h4 className="text-md font-semibold text-gray-900 mb-3">Equipment Status</h4>
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2 px-3 font-semibold text-gray-700">Equipment</th>
            <th className="text-center py-2 px-3 font-semibold text-gray-700">Status</th>
            <th className="text-right py-2 px-3 font-semibold text-gray-700">Usage</th>
          </tr>
        </thead>
        <tbody>
          {sampleData.equipment.map((item: any, index: number) => (
            <tr key={index} className="border-b border-gray-200">
              <td className="py-2 px-3 text-gray-600">{item.name}</td>
              <td className="py-2 px-3 text-center">
                <span className={`inline-block px-2 py-1 rounded text-xs font-medium ${
                  item.status === "Operational"
                    ? "bg-green-100 text-green-700"
                    : "bg-red-100 text-red-700"
                }`}>
                  {item.status}
                </span>
              </td>
              <td className="py-2 px-3 text-right font-medium text-gray-900">{item.usage}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// Generic Report Content
function GenericReportContent({ report, data }: { report: ReportData; data?: any }) {
  return (
    <div>
      <h3 className="text-lg font-bold text-gray-900 mb-4">Report Content</h3>
      <div className="bg-gray-50 border border-gray-300 rounded p-4">
        <p className="text-sm text-gray-600 mb-3">
          This is a sample report preview. The actual report will contain data based on the
          configured parameters and filters.
        </p>

        <div className="space-y-2 text-sm">
          <div className="flex justify-between">
            <span className="font-semibold text-gray-700">Report Period:</span>
            <span className="text-gray-600">
              {format(new Date(), "MMMM yyyy")}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="font-semibold text-gray-700">Generated By:</span>
            <span className="text-gray-600">System Administrator</span>
          </div>
          <div className="flex justify-between">
            <span className="font-semibold text-gray-700">Status:</span>
            <span className="text-gray-600">{report.status}</span>
          </div>
        </div>

        <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded">
          <p className="text-xs text-blue-700">
            <strong>Note:</strong> This is a preview. Generate the report to see actual data.
          </p>
        </div>
      </div>
    </div>
  )
}
